version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: postgres:latest
    container_name: postgres_container
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_DB: faculdade
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/webapi
    volumes:
      - webapi:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - db

volumes:
  webapi:
