// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Tathiane Souza"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/aluno": {
            "get": {
                "description": "Busca todos os alunos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Aluno"
                ],
                "summary": "Busca todos os alunos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria um aluno, os campos que devem ser enviados são: nome e cpf",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Aluno"
                ],
                "summary": "Cria um aluno",
                "parameters": [
                    {
                        "description": "aluno",
                        "name": "aluno",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    }
                }
            }
        },
        "/aluno/curso/{id}": {
            "get": {
                "description": "Realiza um filtro para obter todos os alunos de um curso",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Aluno"
                ],
                "summary": "Filtra alunos por curso",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do curso",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    }
                }
            }
        },
        "/aluno/disciplina/{id}": {
            "get": {
                "description": "Realiza um filtro para obter todos os alunos de uma disciplina",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Aluno"
                ],
                "summary": "Filtra alunos por disciplina",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do disciplina",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    }
                }
            }
        },
        "/aluno/faculdade/{id}": {
            "get": {
                "description": "Realiza um filtro para obter todos os alunos de uma faculdade",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Aluno"
                ],
                "summary": "Filtra alunos por faculdade",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID da faculdade",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    }
                }
            }
        },
        "/aluno/total/{id}": {
            "get": {
                "description": "Realiza um filtro para obter o total de alunos de uma faculdade",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Aluno"
                ],
                "summary": "Filtra o total de alunos de uma faculdade",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do faculdade",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    }
                }
            }
        },
        "/aluno/{id}": {
            "get": {
                "description": "Busca aluno por id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Aluno"
                ],
                "summary": "Busca aluno por id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do aluno",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    }
                }
            },
            "put": {
                "description": "Edita um aluno, os campos que devem ser enviados são: nome e cpf",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Aluno"
                ],
                "summary": "Edita um aluno",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do aluno",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "aluno",
                        "name": "aluno",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta um aluno",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Aluno"
                ],
                "summary": "Deleta um aluno",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do aluno",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/curso": {
            "get": {
                "description": "Busca todos os cursos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Curso"
                ],
                "summary": "Buscar todos os cursos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Curso"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria um curso, os campos que devem ser enviados são: nome e \"faculdade_unique_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Curso"
                ],
                "summary": "Cria um curso",
                "parameters": [
                    {
                        "description": "curso",
                        "name": "curso",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Curso"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Curso"
                        }
                    }
                }
            }
        },
        "/curso-disciplina": {
            "get": {
                "description": "Busca todos os cursoDisciplinas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller CursoDisciplina"
                ],
                "summary": "Buscar todos os cursoDisciplionas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CursoDisciplina"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria um cursoDisciplionas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller CursoDisciplina"
                ],
                "summary": "Cria um cursoDisciplionas",
                "parameters": [
                    {
                        "description": "cursoDiscipliona",
                        "name": "cursoDiscipliona",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CursoDisciplina"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.CursoDisciplina"
                        }
                    }
                }
            }
        },
        "/curso-disciplina/{id}": {
            "get": {
                "description": "Busca cursoDisciplina por id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller CursoDisciplina"
                ],
                "summary": "Busca cursoDisciplina por id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do cursoDisciplina",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CursoDisciplina"
                        }
                    }
                }
            },
            "put": {
                "description": "Edita um cursoDiscipliona, os campos que devem ser enviados são: curso_unique_id e \"disciplina_unique_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller CursoDisciplina"
                ],
                "summary": "Edita um cursoDiscipliona",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do cursoDiscipliona",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "cursoDiscipliona",
                        "name": "cursoDiscipliona",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CursoDisciplina"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CursoDisciplina"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta um cursoDiscipliona, os campos que devem ser enviados são: curso_unique_id e \"disciplina_unique_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller CursoDisciplina"
                ],
                "summary": "Deleta um cursoDiscipliona",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do cursoDiscipliona",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/curso/{id}": {
            "get": {
                "description": "Busca curso por id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Curso"
                ],
                "summary": "Busca curso por id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do curso",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Curso"
                        }
                    }
                }
            },
            "put": {
                "description": "Edita um curso, os campos que devem ser enviados são: nome e \"faculdade_unique_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Curso"
                ],
                "summary": "Edita um curso",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do curso",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "curso",
                        "name": "curso",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Curso"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Curso"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta um curso",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Curso"
                ],
                "summary": "Deleta um curso",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do curso",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/disciplina": {
            "get": {
                "description": "Busca todas as disciplinas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Disciplina"
                ],
                "summary": "Buscar todas as disciplinas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Disciplina"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria uma disciplina, os campos que devem ser enviados são: nome e professor_unique_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Disciplina"
                ],
                "summary": "Cria uma disciplina",
                "parameters": [
                    {
                        "description": "disciplina",
                        "name": "disciplina",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Disciplina"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Disciplina"
                        }
                    }
                }
            }
        },
        "/disciplina-matricula": {
            "get": {
                "description": "Busca todas as disciplinas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller DisciplinaMatricula"
                ],
                "summary": "Buscar todas as disciplinas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DisciplinaMatricula"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria uma disciplinaMatricula, os campos que devem ser enviados são: aluno_unique_id e curso_disciplina_unique_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller DisciplinaMatricula"
                ],
                "summary": "Cria uma disciplinaMatricula",
                "parameters": [
                    {
                        "description": "disciplinaMatricula",
                        "name": "disciplinaMatricula",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DisciplinaMatricula"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.DisciplinaMatricula"
                        }
                    }
                }
            }
        },
        "/disciplina-matricula/{id}": {
            "get": {
                "description": "Busca disciplinaMatricula por id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller DisciplinaMatricula"
                ],
                "summary": "Busca disciplinaMatricula por id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do disciplinaMatricula",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DisciplinaMatricula"
                        }
                    }
                }
            },
            "put": {
                "description": "Edita uma disciplinaMatricula, os campos que devem ser enviados são: aluno_unique_id e curso_disciplina_unique_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller DisciplinaMatricula"
                ],
                "summary": "Edita uma disciplinaMatricula",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID da disciplinaMatricula",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "disciplinaMatricula",
                        "name": "disciplinaMatricula",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DisciplinaMatricula"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DisciplinaMatricula"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta uma disciplinaMatricula",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller DisciplinaMatricula"
                ],
                "summary": "Deleta uma disciplinaMatricula",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID da disciplinaMatricula",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/disciplina/aluno/{id}": {
            "get": {
                "description": "Realiza um filtro para obter quais disciplinas um determinado aluno cursa",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Disciplina"
                ],
                "summary": "Filtra disciplinas que um determinado aluno cursa",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do aluno",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Disciplina"
                        }
                    }
                }
            }
        },
        "/disciplina/{id}": {
            "get": {
                "description": "Busca disciplina por id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Disciplina"
                ],
                "summary": "Busca disciplina por id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do disciplina",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Disciplina"
                        }
                    }
                }
            },
            "put": {
                "description": "Edita uma disciplina, os campos que devem ser enviados são: nome e professor_unique_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Disciplina"
                ],
                "summary": "Edita uma disciplina",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID da disciplina",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "disciplina",
                        "name": "disciplina",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Disciplina"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Disciplina"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta uma disciplina",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Disciplina"
                ],
                "summary": "Deleta uma disciplina",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID da disciplina",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/faculdade": {
            "get": {
                "description": "Busca todas as faculdades",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Faculdade"
                ],
                "summary": "Buscar todas as faculdades",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Faculdade"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria uma faculdade, os campos que devem ser enviados são: nome e cnpj",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Faculdade"
                ],
                "summary": "Cria uma faculdade",
                "parameters": [
                    {
                        "description": "faculdade",
                        "name": "faculdade",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Faculdade"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Faculdade"
                        }
                    }
                }
            }
        },
        "/faculdade/{id}": {
            "get": {
                "description": "Busca faculdade por id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Faculdade"
                ],
                "summary": "Busca faculdade por id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do faculdade",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Faculdade"
                        }
                    }
                }
            },
            "put": {
                "description": "Edita uma faculdade, os campos que devem ser enviados são: nome e cnpj",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Faculdade"
                ],
                "summary": "Edita uma faculdade",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID da faculdade",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "faculdade",
                        "name": "faculdade",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Faculdade"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Faculdade"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta uma faculdade",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Faculdade"
                ],
                "summary": "Deleta uma faculdade",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID da faculdade",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/professor": {
            "get": {
                "description": "Busca todos os professors",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Professor"
                ],
                "summary": "Buscar todos os professors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Professor"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria um professor, os campos que devem ser enviados são: nome e formacao",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Professor"
                ],
                "summary": "Cria um professor",
                "parameters": [
                    {
                        "description": "professor",
                        "name": "professor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Professor"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Professor"
                        }
                    }
                }
            }
        },
        "/professor/{id}": {
            "get": {
                "description": "Busca professor por id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Professor"
                ],
                "summary": "Busca professor por id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do professor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Professor"
                        }
                    }
                }
            },
            "put": {
                "description": "Edita um professor, os campos que devem ser enviados são: nome e formacao",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Professor"
                ],
                "summary": "Edita um professor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do professor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "professor",
                        "name": "professor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Professor"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Professor"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta um professor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Controller Professor"
                ],
                "summary": "Deleta um professor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UniqueID do professor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Aluno": {
            "type": "object",
            "required": [
                "cpf",
                "nome"
            ],
            "properties": {
                "cpf": {
                    "type": "string"
                },
                "disciplina_matriculas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DisciplinaMatricula"
                    }
                },
                "nome": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "integer"
                }
            }
        },
        "models.Curso": {
            "type": "object",
            "properties": {
                "curso_disciplinas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CursoDisciplina"
                    }
                },
                "faculdade": {
                    "$ref": "#/definitions/models.Faculdade"
                },
                "faculdade_unique_id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "integer"
                }
            }
        },
        "models.CursoDisciplina": {
            "type": "object",
            "properties": {
                "curso": {
                    "$ref": "#/definitions/models.Curso"
                },
                "curso_unique_id": {
                    "type": "integer"
                },
                "disciplina": {
                    "$ref": "#/definitions/models.Disciplina"
                },
                "disciplina_matriculas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DisciplinaMatricula"
                    }
                },
                "disciplina_unique_id": {
                    "type": "integer"
                },
                "unique_id": {
                    "type": "integer"
                }
            }
        },
        "models.Disciplina": {
            "type": "object",
            "properties": {
                "curso_disciplinas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CursoDisciplina"
                    }
                },
                "nome": {
                    "type": "string"
                },
                "professor": {
                    "$ref": "#/definitions/models.Professor"
                },
                "professor_unique_id": {
                    "type": "integer"
                },
                "unique_id": {
                    "type": "integer"
                }
            }
        },
        "models.DisciplinaMatricula": {
            "type": "object",
            "properties": {
                "aluno": {
                    "$ref": "#/definitions/models.Aluno"
                },
                "aluno_unique_id": {
                    "type": "integer"
                },
                "curso_disciplina": {
                    "$ref": "#/definitions/models.CursoDisciplina"
                },
                "curso_disciplina_unique_id": {
                    "type": "integer"
                },
                "data_matricula": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "integer"
                }
            }
        },
        "models.Faculdade": {
            "type": "object",
            "required": [
                "cnpj",
                "nome"
            ],
            "properties": {
                "cnpj": {
                    "type": "string"
                },
                "cursos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Curso"
                    }
                },
                "nome": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "integer"
                }
            }
        },
        "models.Professor": {
            "type": "object",
            "required": [
                "formacao",
                "nome"
            ],
            "properties": {
                "disciplinas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Disciplina"
                    }
                },
                "formacao": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "unique_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API Faculdade passei direto",
	Description:      "Esta é a documentação API em Golang",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
